# Config file for Air

# Root directory where the project is located
root = "."
tmp_dir = "tmp"
build_dir = "tmp"

# Command for building the Go app
build = "go build -o ./tmp/main ./cmd/chatapp"

# Command for running the Go app
bin = "tmp/main"

# Watch these directories for changes
[watcher]
  include = [
    "**/*.go",
    "**/*.tmpl",
    "**/*.html"
  ]
  exclude = [
    "tmp",
    "vendor"
  ]
