apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosocket
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-frontend-image:tag
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
