services:
  goapp:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mysql_db
    ##- kafka
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/app
    networks:
      - backend

  # kafka:
  #    image: 'bitnami/kafka:latest'
  #    ports:
  #     - "9092:9092"
  #    networks:
  #      - backend
  #    environment:
  #      - KAFKA_CFG_NODE_ID=0
  #      - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3000:80
    depends_on:
      - mysql_db
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

networks:
  backend:
    driver: bridge
