services:
  goapp:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/app
    networks:
      - backend

  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    networks:
      - backend

networks:
  backend:
    driver: bridge
